type TProperty = {
  id: string;
  brokerId: string;
  realEstateId: string;
  title: string;
  isActive: boolean;
  state: string;
  street: string;
  city: string;
  amountBedrooms: number;
  amountBathrooms: number;
  amountGarage: number;
  valueCondominium: string;
  iptu: string;
  valueRental: string;
  valueSell: string;
  isSelling: boolean;
  isRenting: boolean;
  type: string;
};
